import Head from "next/head";
import { Container } from "@chakra-ui/layout";
import { Button, Flex, Text, Heading } from "@chakra-ui/react";
import { useAuth } from "../context/authContext";
import FileList from "../FileList";
import CreateFolder from "../CreateFolder";
import UploadFile from "../UploadFile";

const Main = ({ title, files, onChange, currentPath }) => {
  const { authToken } = useAuth();

  const handleLogin = () => {
    const CLIENT_ID = "s4ngwjneimiqbs2";
    const REDIRECT_URI = "http://localhost:3000/auth";
    window.location.href = `https://www.dropbox.com/oauth2/authorize?client_id=${CLIENT_ID}&redirect_uri=${encodeURIComponent(
      REDIRECT_URI
    )}&response_type=code`;
  };

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Container maxW="container.lg">
        {!authToken ? (
          <Flex
            width="100%"
            height="100vh"
            alignItems="center"
            justifyContent="center"
            direction="column"
            gap="25px"
          >
            <Text>Please login with Dropbox to continue.</Text>
            <Button
              align="center"
              bg="#3d67ff"
              color="white"
              _hover={{ bg: "#3153cc" }}
              onClick={handleLogin}
            >
              Login with Dropbox
            </Button>
          </Flex>
        ) : (
          <>
            <Flex w="100%" mt="30px" alignItems="center" gap="25px">
              <CreateFolder onChange={onChange} currentPath={currentPath} />
              <UploadFile onChange={onChange} currentPath={currentPath} />
            </Flex>
            <Heading size="lg" mt="30px">
              main{currentPath}
            </Heading>
            <FileList
              files={files}
              onChange={onChange}
              currentPath={currentPath}
            />
          </>
        )}
      </Container>
    </>
  );
};

export default Main;
